spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://2p277534k9.iok.la:13301/test?useSSL=false
    username: root
    password: 123456
  jpa:
   hibernate:
     ddl-auto: create
   show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
server:
  port: 8080
  context-path: /law_consult